"""work model added.

Revision ID: a6c80165c3b7
Revises: 9365536a16b3
Create Date: 2021-12-16 21:02:51.024725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c80165c3b7'
down_revision = '9365536a16b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_title', sa.String(length=100), nullable=True),
    sa.Column('work_client_name', sa.String(length=100), nullable=True),
    sa.Column('work_img', sa.String(length=250), nullable=True),
    sa.Column('work_url', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    # ### end Alembic commands ###
